language: php

php:
  - 5.6

env:
  global:
    - setup=basic

services:
  - mysql

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction
  - chmod -R 777 storage
  - php artisan key:generate --no-interaction

script:
  - php artisan migrate --env=testing --no-interaction -vvv
  - php artisan serve --port=8000 --host=localhost &
  - vendor/bin/phpunit