language: php

php:
  - 5.6

env:
  global:
    - setup=basic

services:
  - mysql

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate:install --env=testing --no-interaction -vvv


script:
  - php artisan migrate --env=testing --no-interaction -vvv
  - php artisan db:seed --env=testing --no-interaction -vvv
  - php artisan db:seed --no-interaction --class=UsersTableSeeder
  - php artisan db:seed --no-interaction --class=UserTypesTableSeeder


  - php artisan serve >/dev/null 2>&1 &
  - vendor/bin/phpunit