language: php

php:
  - 5.6

env:
  global:
    - setup=basic

services:
  - mysql

before_script:
  - cd core
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - chmod -R 777 storage
  - cd ..
  - composer self-update
  - composer install
  - php artisan key:generate --no-interaction

script:
  - php artisan migrate --env=testing --no-interaction -vvv
  - php artisan db:seed --no-interaction --class=UsersTableSeeder
  - php artisan db:seed --no-interaction --class=UserTypesTableSeeder
  - php artisan db:seed --no-interaction --class=CategoriesTableSeeder
  - php artisan db:seed --no-interaction --class=ProductsTableSeeder
  - php artisan db:seed --no-interaction --class=SettingsTableSeeder
  - php artisan db:seed --no-interaction --class=PluginsTableSeeder
  - php artisan db:seed --no-interaction --class=ThemesTableSeeder
  - php artisan serve --port=8000 --host=localhost &
  - cd core
  - vendor/bin/phpunit